[font]
#normal.family = "Comic Mono"
#normal.family = "Comic Shanns"
#normal.family = "ComicShannsMono Nerd Font"
#normal.family = "Comic Code Demo"
#normal.family = "CaskaydiaCove"
normal.family = "UbuntuMono Nerd Font"
#size = 17
size = 18 # Ubuntu Mono

[window]
opacity = 0.9
